Badges
rublen/TestGuru pull request #17
Opened 2018-08-19 05:22 UTC by rublen

2018-08-19 11:36 UTC, psylone requested changes

2018-08-19 11:36 UTC, psylone commented on db/migrate/20180817181412_create_users_badges.rb
> +    create_table :users_badges, id: false do |t|
Практика показывает что `id` и `timestamps` даже в таких случаях лучше оставлять.

2018-08-19 11:36 UTC, psylone commented on app/models/user.rb
> +  def scope_completed?(scope)
Если мы проверяем только `:elementary`, стоит отразить это в названии метода.

2018-08-19 11:36 UTC, psylone commented on app/models/user.rb
> +  def scope_completed?(scope)
Вообще, параметр это же не `scope`, это уровень сложности метода. `scope` это метод модели ActiveRecord, и этот термин не зависит от бизнес-логики.

2018-08-19 11:36 UTC, psylone commented on app/models/user.rb
> +      test.test_passages.any? { |tp| tp.score >= 80 }
Всю эту логику стоит сделать средствами ActiveRecord (в конечном итоге - средствами SQL).

2018-08-19 11:36 UTC, psylone commented on app/models/user.rb
> +      test.test_passages.any? { |tp| tp.score >= 80 }
Возможно, для этого придётся добавить атрибут в таблицу `test_passages` чтобы понимать пройден тест или нет.

2018-08-19 11:36 UTC, psylone commented on app/models/badge.rb
> +  # criterion is one of: %w[well_done hundred first_attempt elementary intermediate advanced]
`elementary, intermediate, advanced` - это по факту одно и то же правило.

2018-08-19 11:36 UTC, psylone commented on app/models/badge.rb
> +  validates :criterion, presence: true, uniqueness: true
Если делаешь валидацию на уникальность, нужно обязательно добавить уникальный индекс в БД.

2018-08-19 11:36 UTC, psylone commented on app/models/badge.rb
> +      find_by_criterion('well_done')
Это тоже по сути одно и то же правило, просто граница `score` различается. А если будет ещё один рубеж: 70, и ещё один: 75? Придётся городить огород из условий.

2018-08-19 11:36 UTC, psylone commented on app/models/badge.rb
> +      find_by_criterion('well_done')
Выгодней хранить 2 атрибута в бэйдже: `rule_name` и `rule_value`. Тогда достаточно определить один метод для каждого типа правила, а в `rule_value` будет храниться конкретное значение для конкретного бэйджа.

Например, может быть бэйдж с правилом `passed_for_level`, и можно будет создать 2 бэйджа для начального уровня и продвинутого. Но при этом будет в коде у нас только один метод который успешно будет разруливать логику для обоих значений.

2018-08-19 11:36 UTC, psylone commented on app/models/badge.rb
> +      give_badge('advanced', user) if user.scope_completed?(:advanced)
Если будут добавляться ещё уровни, придётся обновлять код и здесь.

2018-08-19 11:36 UTC, psylone commented on app/models/user.rb
> +  def scope_completed?(scope)
В принципе я понимаю смысл названия `scope` в контексте пройденных тестов, но лучше назвать это иначе.

2018-08-19 11:36 UTC, psylone commented on app/models/badge.rb
> +      badge unless user.badges.include? badge
Это условие лучше проверять отдельно выше. По сути мы не здесь присваиваем бэйдж пользователю, здесь мы бэйдж только ищем.

2018-08-19 11:36 UTC, psylone commented on app/controllers/test_passages_controller.rb
> +  def earned_badges
Это неплохо, но в контроллере этого кода не должно быть поскольку это бизнес-логика )

Кроме того, при добавлении нового правила тебе придётся менять код в нескольких местах: здесь и в модели бэйджа.

2018-08-20 04:32 UTC, rublen commented on app/models/badge.rb
> +  validates :criterion, presence: true, uniqueness: true
не пойму, что происходит: хочу добавить `unique: true`, мигорация проходит нормально, а в схеме `unique: true` не отображается:
![image](https://user-images.githubusercontent.com/16900457/44320503-106ecf00-a44b-11e8-82f7-6af0f6e59d0b.png)

2018-08-20 06:56 UTC, rublen commented on db/migrate/20180817181412_create_users_badges.rb
> +    create_table :users_badges, id: false do |t|
добавила. В sqlite эти поля добавлялись автоматически, в postgresql id добавляетя, а timestamps, получается, нет, т.е. timestamps нужно всегда явно указывать в миграции?

2018-08-20 07:44 UTC, rublen commented on app/models/user.rb
> +    passed_tests_by_scope(:elementary).count == Test.send(scope).count
да, тут ошибка, вместо `:elementary` должно было быть `scope` (теперь уже `layer`)

2018-08-20 07:45 UTC, rublen commented on app/models/user.rb
> +  def scope_completed?(scope)
` layer` - ничего лучше не могу придумать

2018-08-20 07:49 UTC, rublen commented on app/models/user.rb
> +      test.test_passages.any? { |tp| tp.score >= 80 }
ожидала это замечание) Добавила `score:integer`

2018-08-20 08:37 UTC, rublen commented on app/models/badge.rb
> +      find_by_criterion('well_done')
значит меняю у бейджа свое поле `criterion` на `rule_value` и добавляю поле `rule_name`

2018-08-20 11:03 UTC, rublen commented on app/models/badge.rb
> +      find_by_criterion('well_done')
и создаю составной уникальный индекс

2018-08-20 11:04 UTC, rublen commented on app/models/user.rb
> +  def scope_completed?(scope)
complexity

2018-08-22 10:27 UTC, psylone commented on app/models/badge.rb
> +      find_by_criterion('well_done')
Да.

2018-08-22 10:44 UTC, psylone approved these changes

2018-08-22 10:44 UTC, psylone commented on app/models/badge.rb
> +    ['by_score', 'from_first_attempt', 'by_complexity']
Это можно вынести в константу.

2018-08-22 10:44 UTC, psylone commented on app/models/badge.rb
> +    ['by_score', 'from_first_attempt', 'by_complexity']
Можно даже сделать хэш:

```ruby
RULES = { by_score: [80, 100] }
```

2018-08-22 10:44 UTC, psylone commented on app/models/user.rb
> +    tests.send(complexity).select { |t| t.test_passages.positive_pass }
Это лучше совсем сделать средствами SQL:

```ruby
tests.public_send(complexity).where('test_passages.score >= 80')
```

2018-08-22 10:44 UTC, psylone commented on app/models/user.rb
> +    passed_tests_by_complexity(complexity).uniq.count == Test.send(complexity).count
Используй `public_send`. Он работает также как обычный `send`, но ищет только среди публичных методов.

2018-08-22 10:44 UTC, psylone commented on app/services/user_badges_service.rb
> +      @earned_badges << badge if send("passed_#{badge.rule_name}?", badge.rule_value)
👍

2018-08-24 14:51 UTC, merged